language: python
python:
  - "3.6"
  #- "3.7" commented due to travis distrib install error / permission denied
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pip install -e .
  - pytest -v tests
