language: python
python:
  - "3.6"
  #- "3.7" commented due to travis distrib install error / permission denied
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
# command to run tests
script:
  - pip install -e .
  - py.test --cov=control_repository
after_success:
  - codecov
