language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install tox codecov
# command to run tests
script:
  - tox -v
after_success:
  - codecov
